# Generated by Django 5.2 on 2025-04-14 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2025, 4, 14, 14, 12, 58, 931389)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 14, 14, 12, 58, 931412)),
        ),
    ]
